# PostgreSQL
postgres:
    image: postgres:9.6.0
    ports:
      - 5432:5432 # Bind host port 5432 to PostgreSQL port 5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD={{ cookiecutter.project_slug }}
      - POSTGRES_USER={{ cookiecutter.project_slug }}

# Django app
app:
    build: .
    command: dev
#    command: uwsgi
    ports:
      - 8000:8000
      - 8001:8001
    volumes:
      - ./app:/usr/src/app
    links:
      - postgres:postgres

redis:
  image: redis
  ports:
    - 6379:6379