postgres:
  image: postgres:9.6.0
  volumes:
    - ./pgdata:/var/lib/postgresql/data
  environment:
    - LC_ALL=C.UTF-8
    - POSTGRES_PASSWORD={{ cookiecutter.project_slug }}
    - POSTGRES_USER={{ cookiecutter.project_slug }}
  ports:
    - 5432:5432

app:
  build: .
  command: gunicorn {{ cookiecutter.project_slug }}.wsgi -b 0.0.0.0:8000 
  working_dir: /app
  ports:
    - 8000:8000
    - 8001:8001
  volumes:
    - ./:/app
  links:
    - postgres:postgres
    - redis:redis

redis:
  image: redis
  ports:
    - 6379:6379

celery:
  build: .
  command: celery -A {{ cookiecutter.project_slug }} worker -E -B --loglevel=DEBUG
  working_dir: /app
  links:
    - postgres:postgres
    - redis:redis


