# PostgreSQL
postgres:
    image: postgres:9.6.0
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD={{ cookiecutter.project_slug }}
      - POSTGRES_USER={{ cookiecutter.project_slug }}

# Django app
app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000 -v2
    working_dir: /app
    ports:
      - 8000:8000
      - 8001:8001
    volumes:
      - ./:/app
    links:
      - postgres:postgres
      - redis:redis

redis:
  image: redis
  ports:
    - 6379:6379